name: Publish to Cargo

on:
  push:


jobs:
  publish:
    runs-on: ubuntu-latest

    name: "publish"

    environment: cargo

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Run publish-action
        uses: tu6ge/publish-action@v0.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
